Feature/cmob 2006 create UI
anadzebniauri/MovieApp pull request #4
Opened 2023-08-09 08:58 UTC by anadzebniauri

2023-08-09 13:51 UTC, anadzam commented on MovieApp/Scenes/HomePage/SearchBar.swift
> +        textField.layer.cornerRadius = Constants.SearchBar.cornerRadius
corner radiusi mgoni unda daapatarao ro upro momrgvalebuli ikos textfieldi. ro davrane cacvetebulia da dizains ar emtxveva. me iphone 14 proze davrane da sheuleba magito mara naxe mokled

2023-08-09 13:51 UTC, anadzam commented on MovieApp/Scenes/FavoritesPage/FavoriteMoviesViewController.swift
favoritebis gverdze bugia tabbarebis buttonebtan, ar chans da epareba collectionview. mgoni prosta constrainetbi gak gasaceri tabbaris  topze
![Simulator Screenshot - iPhone 14 Pro - 2023-08-09 at 17 00 48](https://github.com/anadzebniauri/MovieApp/assets/84043643/52ded906-a2cb-42f7-882d-5e62ef2204fb)
![Simulator Screenshot - iPhone 14 Pro - 2023-08-09 at 17 00 53](https://github.com/anadzebniauri/MovieApp/assets/84043643/6ac43366-367d-4a05-ab2f-e9b25832cd36)

2023-08-09 13:51 UTC, anadzam commented on MovieApp/Scenes/HomePage/SearchBar.swift
> +    func collectionView(_ collectionView: UICollectionView, didDeselectItemAt indexPath: IndexPath) {
arvici es ramdenad scoria mara mgoni jansr ro monishnav magisi deselectic unda shegedzlos da shen shemtxvevashi ari ro deselecti ar xdeba. anu magalitad pirveli monishne da magisi deselecti xdeba roca meores daacher mara arcerti ro agar ikos monishnuli eg gak mgoni dasamatebeli

2023-08-09 13:51 UTC, anadzam commented on MovieApp/Scenes/DetailsPage/DetailsComponentsView.swift
Scenebis fileshi rogorc vici marto Controllerebi da shesabamisi viewModelebi unda gkondes. Cutom viewebi unda gkondes Core fileshi sadac gekneba Custom UI is file. es chatis appze tkves egre da me magas mivkvebi egre. mokled tu egrea mashin kvela custom ui componenti da cellebi unda gkondes calke.

2023-08-10 13:07 UTC, Niklaus2000 commented on MovieApp/Core/CustomUI/DetailsComponentsView.swift
> +        label.font = UIFont.bold(ofSize: Constants.Title.fontSize)
ლეიბლის  ფონტი შეგიძლია ასე გაიტანო
static let textFont = UIFont.bold(ofSize: 20) და მერე ასე დაუსეტო 
label.font =  Constants.Title.fontSize

2023-08-10 13:07 UTC, Niklaus2000 commented on MovieApp/Core/CustomUI/DetailsComponentsView.swift
ისედაც დიდი ფაილია და ამფაილის კონსტანტები რომ გაიტანო სხვა group კაი იქნება. ასეთი იერარქია რომ გააკეთო  CustomUI->MoviesView,DetailsView->DetailsView,DetailView+Constants,და  ასე შემდეგ

2023-08-10 13:07 UTC, Niklaus2000 commented on MovieApp/Core/CustomUI/SearchBar.swift
> +        return 2
return  წაშალე მის გარეშეც იმუშავებს

2023-08-10 13:07 UTC, Niklaus2000 commented on MovieApp/Scenes/LoadingPage/LoadingViewController.swift
კონტროლერი ზოგადად მძიმეა.  LoadingViewController  ფაილი რატომ  UIViewController  - ად   და არა უივიუვდ?.

2023-08-10 13:07 UTC, Niklaus2000 commented on MovieApp/Scenes/HomePage/HomeModel.swift
model - ს ზოგადად Core  - ში ამატებენ ან  თუ არ გჭირდება  წაშალე.

2023-08-10 13:07 UTC, Niklaus2000 commented on MovieApp/Scenes/ErrorPage/ErrorViewController.swift
UIViewController UIView - ად  გადააკეთე

2023-08-10 13:11 UTC, anadzebniauri commented on MovieApp/Core/CustomUI/DetailsComponentsView.swift
> +        label.font = UIFont.bold(ofSize: Constants.Title.fontSize)
extensionში მაქვს გატანილი ეგ ფონტები, ყოველ ჯერზე კონსტანტებში რო არ წერო ყველა ფაილში მაგიტო ექსთენშენით არის გაკეთებული

2023-08-10 13:12 UTC, anadzebniauri commented on MovieApp/Core/CustomUI/DetailsComponentsView.swift
ეს ინდივიდუალურია

2023-08-10 13:25 UTC, anadzebniauri commented on MovieApp/Scenes/LoadingPage/LoadingViewController.swift
navigation controller-ის გამო რადგან ეს ცალკე ფეიჯია და ნავიგაციისთვის მჭირდება ამიტომ ვიუ კონტროლერია

2023-08-10 13:35 UTC, Niklaus2000 approved these changes

2023-08-10 13:37 UTC, anadzam approved these changes

2023-08-10 15:16 UTC, tivanashvili requested changes

2023-08-10 15:16 UTC, tivanashvili commented on MovieApp/Core/CustomUI/SearchBar.swift
> +    var selectedIndex:IndexPath?
private

2023-08-10 15:16 UTC, tivanashvili commented on MovieApp/Core/CustomUI/SearchBar.swift
> +        searchBar.delegate = self
es searchbaris closureshi gaitane, private lazy var - ad gadaakete searchBar-is closure da chveulebrivad imushavebs

2023-08-10 15:16 UTC, tivanashvili commented on MovieApp/Core/CustomUI/NavigationBar.swift
> +    lazy var homeButton: UIButton = {
es private under ikos, arc lazy chirdeba, ertaderti private let ro gadaaketeb addtargeti geqneba calke gasatani

2023-08-10 15:16 UTC, tivanashvili commented on MovieApp/Core/CustomUI/NavigationBar.swift
> +        let button = UIButton(configuration: config)
esec private

2023-08-10 15:16 UTC, tivanashvili commented on MovieApp/Core/CustomUI/NavigationBar.swift
> +    lazy var favoritesButton: UIButton = {
private

2023-08-10 15:16 UTC, tivanashvili commented on MovieApp/Core/CustomUI/DetailsView.swift
> +class DetailsView: UIView {
ყველას კლასს დაუწერე final თუ შვილი კლასი არ დაგჭირდება

2023-08-10 15:16 UTC, tivanashvili commented on MovieApp/Core/Cell/CategoryCell.swift
> +    private lazy var categoryLabel: UILabel = {
aq lazy var ar gchirdeba, private let

2023-08-10 15:16 UTC, tivanashvili commented on MovieApp/Scenes/HomePage/HomeViewController.swift
> +    private let searchBar = SearchBar()
13-14 line closurebad gadaakete da func shi rac gaqvs aq shemoitane

2023-08-10 15:16 UTC, tivanashvili commented on MovieApp/Scenes/FavoritesPage/FavoriteMoviesViewController.swift
> +    private let navigationBar = NavigationBar()
edenic closurebad gadaakete

2023-08-10 15:16 UTC, tivanashvili commented on MovieApp/Scenes/DetailsPage/DetailsViewController.swift
> +    private let scrollView = UIScrollView()
edenic closurebad 13-16 line

2023-08-10 15:16 UTC, tivanashvili commented on MovieApp/Scenes/LoadingPage/LoadingViewController.swift
> +    var loadingView: UIView!
private da safe unwrap

2023-08-10 15:16 UTC, tivanashvili commented on MovieApp/Scenes/LoadingPage/LoadingViewController.swift
> +    func setupLoadingView() {
private

2023-08-10 15:16 UTC, tivanashvili commented on MovieApp/Scenes/LoadingPage/LoadingViewController.swift
> +    func animateLoading() {
private

2023-08-11 06:32 UTC, anadzebniauri commented on MovieApp/Core/CustomUI/NavigationBar.swift
> +    lazy var homeButton: UIButton = {
lazy imitoa ro self idzaxebs add targeti

2023-08-11 06:41 UTC, anadzebniauri commented on MovieApp/Scenes/HomePage/HomeViewController.swift
> +    private let searchBar = SearchBar()
მგონი ამის ქლოჟერად გატანას აზრი არ აქვს კონსტრეინტებს ვუსეტავ

2023-08-11 06:42 UTC, anadzebniauri commented on MovieApp/Scenes/DetailsPage/DetailsViewController.swift
> +    private let scrollView = UIScrollView()
აქაც კონსტრეინტები მაქვს დ აარ უნდა ქლოჟერი

2023-08-11 07:17 UTC, tivanashvili approved these changes

2023-08-11 07:19 UTC, tivanashvili approved these changes

2023-08-11 07:27 UTC, giga-khizanishvili approved these changes

2023-08-11 07:32 UTC, merged

2023-08-11 07:32 UTC, Niklaus2000 approved these changes